services:
  nginx:
    container_name: ${CONTAINER_PREFIX:-wp_}server
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/app.conf.template:/etc/nginx/templates/app.conf.template:ro
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      PROXY_NAME: ${PROXY_NAME:-localhost}
      HOST_NAME: ${HOST_NAME:-localhost}
      ENVIRONMENT: ${ENVIRONMENT:-local}
      ENVIRONMENT_DOMAIN: ${ENVIRONMENT:-test.local}
      SSH_HOST_PRODUCTION: ${SSH_HOST_PRODUCTION:-test.com}
      SSH_HOST_STAGE: ${SSH_HOST_STAGE:-stage.test.com}
      CLIENT_MAX_BODY: ${WORDPRESS_MEMORY_LIMIT:-256M}
    networks:
      - default

  wordpress:
    container_name: ${CONTAINER_PREFIX:-wp_}app
    image: ${CONTAINER_PREFIX:-wp_}wordpress:${WORDPRESS_IMAGE_VERSION:-latest-fpm-alpine}
    build:
      context: ./config
      dockerfile: Dockerfile
      args:
        - WORDPRESS_IMAGE_VERSION=${WORDPRESS_IMAGE_VERSION:-latest-fpm-alpine}
    volumes:
      - ./app:/var/www/html
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/php/sendmail.ini:/usr/local/etc/php/conf.d/sendmail.ini
      - ./config/php/zzz-mail.ini:/usr/local/etc/php/conf.d/zzz-mail.ini:ro
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FORCE_SSL_ADMIN', ${WORDPRESS_FORCE_SSL_ADMIN:-true} );
        define( 'WP_MEMORY_LIMIT', '${WORDPRESS_MEMORY_LIMIT:-256M}' );
        define( 'DISALLOW_FILE_EDIT', ${WORDPRESS_DISALLOW_FILE_EDIT:-true} );
        define( 'WP_ENV', '${WORDPRESS_ENVIRONMENT:-local}' );
        define( 'WPMS_ON', ${WORDPRESS_SMTP_ON:-true} );
        define( 'WPMS_MAILER', '${WORDPRESS_SMTP_MAILER:-smtp}' );
        define( 'WPMS_SMTP_HOST', '${WORDPRESS_SMTP_HOST:-mailpit}' );
        define( 'WPMS_SMTP_PORT', '${WORDPRESS_SMTP_PORT:-1025}' );
        define( 'WPMS_SMTP_AUTH', '${WORDPRESS_SMTP_AUTH:-false}' );
        define( 'WPMS_SMTP_AUTOTLS', '${WORDPRESS_SMTP_AUTOTLS:-false}' );
        define( 'WPMS_SSL', ${WORDPRESS_SMTP_SSL:-''} );
        define( 'AUTOMATIC_UPDATER_DISABLED', '${WORDPRESS_AUTOMATIC_UPDATER_DISABLED:-false}' );
        define( 'WP_AUTO_UPDATE_CORE', '${WORDPRESS_AUTO_UPDATE_CORE:-true}' );
        define( 'DISALLOW_FILE_MODS', '${WORDPRESS_DISALLOW_FILE_MODS:-false}' );
        define( 'WP_POST_REVISIONS', '${WORDPRESS_POST_REVISIONS:-5}' );
        define( 'CONCATENATE_SCRIPTS', '${WORDPRESS_CONCATENATE_SCRIPTS:-true}' );
        define( 'EMPTY_TRASH_DAYS', '${WORDPRESS_EMPTY_TRASH_DAYS:-7}' );
        define( 'COMPRESS_CSS', '${WORDPRESS_COMPRESS_CSS:-true}' );
        define( 'COMPRESS_SCRIPTS', '${WORDPRESS_COMPRESS_SCRIPTS:-true}' );
        define( 'ENFORCE_GZIP', '${WORDPRESS_ENFORCE_GZIP:-true}' );
        define( 'DISABLE_WP_CRON', '${WORDPRESS_DISABLE_WP_CRON:-false}' );
      ENVIRONMENT: ${ENVIRONMENT:-local}
      ENVIRONMENT_DOMAIN: ${ENVIRONMENT:-test.local}
      SSH_HOST_PRODUCTION: ${SSH_HOST_PRODUCTION:-test.com}
      SSH_HOST_STAGE: ${SSH_HOST_STAGE:-stage.test.com}
    depends_on:
      wp_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  wp_db:
    container_name: ${CONTAINER_PREFIX:-wp_}db
    image: mariadb:11.4.7
    restart: unless-stopped
    ports:
      - 3306-3399:3306
    volumes:
      - wp_data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_NAME
      MARIADB_USER: $DB_USER
      MARIADB_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - default

  redis:
    container_name: ${CONTAINER_PREFIX:-wp_}redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  wp_data:
    name: ${CONTAINER_PREFIX:-wp_}data
  mail_data:
    name: ${CONTAINER_PREFIX:-wp_}mail_data

networks:
  default:
    driver: bridge
    name: ${CONTAINER_PREFIX:-wp_}network
