services:
  nginx:
    container_name: ${CONTAINER_PREFIX:-wp_}server
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/app.conf.template:/etc/nginx/templates/app.conf.template:ro
      - ./config/nginx/mailpit.conf.template:/etc/nginx/templates/mailpit.conf.template:ro
      - ./config/ssl/local-cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./config/ssl/local-key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      PROXY_NAME: ${PROXY_NAME:-localhost}
      HOST_NAME: ${HOST_NAME:-localhost}
    env_file:
      - .env
    networks:
      - default

  wordpress:
    container_name: ${CONTAINER_PREFIX:-wp_}app
    image: ${CONTAINER_PREFIX:-wp_}wordpress:${WORDPRESS_IMAGE_VERSION:-latest-fpm-alpine}
    build:
      context: ./config
      dockerfile: Dockerfile
      args:
        - WORDPRESS_IMAGE_VERSION=${WORDPRESS_IMAGE_VERSION:-latest-fpm-alpine}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./app:/var/www/html
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/php/sendmail.ini:/usr/local/etc/php/conf.d/sendmail.ini
      - ./config/php/zzz-mail.ini:/usr/local/etc/php/conf.d/zzz-mail.ini:ro
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        define('WP_MEMORY_LIMIT', '2048M');
        define('DISALLOW_FILE_EDIT', true);
        define('WP_ENV', 'local');
        define( 'WPMS_ON', true );
        define( 'WPMS_MAILER', 'smtp' );
        define( 'WPMS_SMTP_HOST', 'mailpit' );
        define( 'WPMS_SMTP_PORT', 1025 );
        define( 'WPMS_SMTP_AUTH', false );
        define( 'WPMS_SMTP_AUTOTLS', false );
        define( 'WPMS_SSL', '' );
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d"
    env_file:
      - .env
    depends_on:
      wp_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  wp_db:
    container_name: ${CONTAINER_PREFIX:-wp_}db
    image: mariadb:11.4.7
    restart: unless-stopped
    ports:
      - 3306-3399:3306
    volumes:
      - wp_data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_NAME
      MARIADB_USER: $DB_USER
      MARIADB_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - default

  redis:
    container_name: ${CONTAINER_PREFIX:-wp_}redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  mailpit:
    image: axllent/mailpit
    container_name: ${CONTAINER_PREFIX:-wp_}mail
    restart: unless-stopped
    volumes:
      - mail_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - default

volumes:
  wp_data:
    name: ${CONTAINER_PREFIX:-wp_}data
  mail_data:
    name: ${CONTAINER_PREFIX:-wp_}mail_data

networks:
  default:
    driver: bridge
    name: ${CONTAINER_PREFIX:-wp_}network
